wandb: {}
project_name: sceneflow
restore_ckpt: None
#restore_ckpt: ./checkpoints/sceneflow/uncertainty4/80000.pth
#restore_ckpt: ./pretrained/sceneflow.pth
logdir: './checkpoints/sceneflow/consistency1/'
encoder: 'vitl'
batch_size: 2
train_datasets: ['sceneflow']
lr: 2e-4
wdecay: 1e-5
total_step: 200000
save_frequency: 100
save_path: ./checkpoints/sceneflow/consistency1/
val_frequency: 100
image_size: [320, 736]
train_iters: 22
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 1
seed: 666
whole_dataset: False
sampler: False
precision_dtype: float16
mixed_precision: False

